apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "harness.name" . }}-job-creator-binding
  labels:
    {{- include "harness.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "harness.name" . }}-runner
roleRef:
  kind: Role
  name: {{ include "harness.name" . }}-job-creator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "harness.name" . }}-restricted-scc
  labels:
    {{- include "harness.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "harness.name" . }}-runner
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:restricted
  apiGroup: rbac.authorization.k8s.io
